config/routes.rb
Rails.application.routes.draw do
  
  get "/hello" => "welcome#hello"
  get "/about" => "about#index"
  get "/questions/new" => "questions#new", as: :new_question
  post "/questions" => "questions#create", as: :questions
  get "/questions/:id" => "questions#show", as: :question
  get "/questions" => "questions#index"
  get "/questions/:id/edit" => "questions#edit", as: :edit_question
  patch "/questions/:id" => "questions#update"  
  delete "/questions/:id" => "questions#destroy"

  root "welcome#index"

end

app/models/question.rb
sclass Question < ActiveRecord::Base
	validates :title, presence: true, uniqueness: {scope: :body, case_sensitive: false }
	validates :body, presence: {message: "must be provided!"}, uniqueness: true
	validates :view_count, numericality: {greater_than_or_equal_to: 0}
	validate :stop_words
	after_initialize :set_defaults
	before_save :capitalize_title

	scope :recent, lambda {|x| order("updated_at DESC").limit(x) }
		#def self.recent(number)
		#order("updated_at DESC").limit(number)
		#end

	#scope :recent, lambda {|x| order("created_at DESC").limit(x) }

	def self.last_days(num)
	   where("created_at >?", num.days.ago)
	end

	private

	def stop_words
		if title.present? && title.include?("monkey")
		errors.add(:title, "Monkey is not allowed!") 
		end
	end

	def set_defaults
		self.view_count ||= 0
	end

	def capitalize_title
		self.title.capitalize!
	end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
	
	def index
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :find_question, only: [:show, :edit, :update, :destroy]
  

  def index
    @questions = Question.all
  end

  def edit
    @question = Question.find params[:id]
  end

  def new 
    @question = Question.new
  end

  def update  
    if @question.update question_params
    render text: params, notice: "Updated Successfully"
    else
    render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: "Deleted Succesfully"
  end

  def create 
    @question = Question.new question_params
    if @question.save 
       #redirect_to question_path(@question.id)
      redirect_to @question, notice: "Created Successfully!"
     else
      render :new
    end
  end

  def show  
    @question.increment!(:view_count)
    #@question.view_count +=1
    #@question.save
    #render text: params
  end

  def find_question
    @question = Question.find params[:id]
  end

  def question_params
  params.require(:question).permit(:title, :body)
  end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def hello
  end

  def index
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>This is our about page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<a href="/">Home</a>
|
<a href="/hello">Hello</a>
|
<a href="/about">About</a>
|
<%= link_to "New Question", new_question_path %>
|
<%= link_to "All Question", questions_path %>
<hr>
<%= flash[:notice] || flash[:error] %>
<hr>
<%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<% if @question.errors.any? %>
 <ul>
  <% @question.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
 <% end %>
</ul>
<% end  %>

<%= form_for @question do |x| %>
  <%= x.label :title %><br>
  <%= x.text_field :title %><br>
  <%= x.label :body %><br>
  <%= x.text_area :body %><br>
  <%= x.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<%= render "form" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% @questions.each do |p| %>
<h2><%= link_to p.title, question_path(p) %></h2>
<p><%= p.body %></p>
<hr>
<% end %>

app/views/questions/new.html.erb
<h1>Create New Questions</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p>View Count: <%= @question.view_count %></p>


<%= link_to "Edit", edit_question_path(@question) %> &nbsp <%= link_to "Delete", question_path(@question), data: {confirm: "Are you sure?"}, method: "delete" %>

app/views/welcome/hello.html.erb
<h1>Hello CodeCore</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome To Awesome Answers</h1>
<p>Find answers to anything here!</p>